# Generated by Django 5.0.2 on 2024-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='EdenToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
