# Generated by Django 5.0.2 on 2024-02-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_edentoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='EdenToken',
            new_name='edentoken',
        ),
    ]
