# Generated by Django 5.0.2 on 2024-02-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textocr',
            field=models.TextField(null=True),
        ),
    ]
